### ISSUE TITLE
No way to open a XLSX locked by password

### ISSUE THREAD

**Issue by mariosil** [woahdae/simple_xlsx_reader#29]
Hi, I just wondering if there is a way to open a `xlsx` spreadsheet which is locked by password.
I even have the password to open that file but I can't find a method in this gem that I could use to open the file.
Something like: **`SimpleXlsxReader.open(xlsx_filename, password)`**

There is something to workaround this use case.

**Comment by woahdae** [comment]
Nope, no explicit support, and I have no idea how passwords work in xlsx
files so I couldn’t say whether a workaround is possible.

**Comment by mariosil** [comment]
Uhh, anyway thanks for answer

**Comment by pcoughlin** [comment]
Any new thoughts on this?
I have the same issue.

**Comment by woahdae** [comment]
I don't have a need for this, but I would welcome a contribution to reading password protected files.

[Here's an NPM project](https://github.com/ankane/secure-spreadsheet) that appears to have implemented password protected XLSX sheets, you could see how they do it.

[Here's the wikipedia page for the feature](https://en.wikipedia.org/wiki/Microsoft_Office_password_protection), although it mostly provides broad background rather than implementation details.

If you could find a command line way to decrypt the files, you could use that first, then this gem. I couldn't find any with a quick googling, but I didn't try very hard.
